import { FONT_SIZES, PALETTE_COLORS } from '@/utilities/theme';
import { SxProps, Theme } from '@mui/material';

export const DetectionResultStepStyle: SxProps = {
  position: 'relative',
  mb: 10,
  p: 1,
  width: {
    xs: '95vw',
    sm: '90vw',
    md: '85vw',
    lg: '70vw',
  },
  minHeight: '600px',
  height: 'fit-content',
  display: 'flex',
  alignItems: 'flex-start',
  flexWrap: 'wrap',
  '& .MuiGrid2-root > .title': {
    fontSize: {
      xs: FONT_SIZES.md,
      sm: FONT_SIZES.lg,
      md: FONT_SIZES.xl,
      lg: FONT_SIZES['2xl'],
    },
  },
  '& .MuiGrid2-root > .MuiPaper-root > .MuiTypography-root.label': {
    fontSize: {
      xs: FONT_SIZES.sm,
      sm: FONT_SIZES.md,
      md: FONT_SIZES.lg,
      lg: FONT_SIZES.xl,
    },
    textTransform: 'lowercase',
  },
  '& .MuiGrid2-root > .MuiPaper-root > .MuiTypography-root.result': {
    fontSize: {
      xs: FONT_SIZES.sm,
      sm: FONT_SIZES.md,
      md: FONT_SIZES.lg,
      lg: FONT_SIZES.xl,
    },
    textTransform: 'capitalize',
  },
  '& .analyse-result-info': {
    '& .title': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 'bold',
      fontSize: FONT_SIZES.xl,
      textAlign: 'center',
    },
    p: 2,
    borderRadius: 5,
    boxShadow: `0.4px 0.4px 2.2px -8px rgba(0, 0, 0, 0.02), 1px 1px 5.3px -8px rgba(0, 0, 0, 0.028), 1.9px 1.9px 10px -8px rgba(0, 0, 0, 0.035), 3.4px 3.4px 17.9px -8px rgba(0, 0, 0, 0.042), 6.3px 6.3px 33.4px -8px rgba(0, 0, 0, 0.05), 15px 15px 80px -8px rgba(0, 0, 0, 0.07)`,
  },
  '& .MuiPaper-root': {
    p: 1,
    my: 1,
    display: 'flex',
    alignItems: 'center',
    boxShadow: 'none',
  },
  gap: 1,
  '& .degradation-rate-title': {
    py: 2,
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: 1,
    width: '100%',
    justifyContent: 'space-between',
    '& .MuiTypography-root': {
      background: PALETTE_COLORS.pine,
      color: '#fff',
      fontWeight: 'bold',
      textAlign: 'center',
      width: 'fit-content',
      textTransform: 'uppercase',
      py: 1,
      px: 2,
      borderRadius: 3,
    },
  },
  '& .degradation-levels': {
    '& .degradation-levels-box': {
      width: 40,
      height: 40,
      borderRadius: 2,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      transition: 'all 500ms',
    },
    '&:hover': {
      '& .degradation-levels-box:not(.degradation-levels-box-selected)': {
        background: '#D9D9D9',
      },
      '& .degradation-levels-box-selected': {
        transform: 'scale(1.2)',
      },
    },
  },
  '& .disclaimer-container': {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
};

export const GetAddressStepStyle: SxProps = {
  width: {
    xs: '90vw',
    md: '80vw',
    lg: '70vw',
  },
  '& .diagnostic-cta': {
    fontWeight: 700,
    textAlign: 'center',
    marginTop: 5,
  },
  '& .location-input': {
    width: {
      xs: '90vw',
      md: '70vw',
      lg: '50vw',
    },
    height: 64,
    marginTop: 2,
    marginBottom: 5,
    display: 'flex',
    alignItems: 'center',
    px: 1.5,
    gap: 1,
    borderRadius: 5,
    backgroundColor: PALETTE_COLORS.white,
    boxShadow: '0 4px 16px -6px rgba(17,39,23,0.18), 0 1px 3px rgba(17,39,23,0.08)',
    transition: 'box-shadow 180ms ease',
    '&:hover': {
      boxShadow: '0 8px 24px -8px rgba(17,39,23,0.22), 0 1px 3px rgba(17,39,23,0.1)',
    },
    '&:focus-within': {
      boxShadow: `0 8px 28px -8px rgba(255,82,27,0.28), 0 0 0 3px rgba(255,82,27,0.14)`,
    },
  },
  '& .location-list': {
    width: {
      xs: '90vw',
      md: '70vw',
      lg: '50vw',
    },
    maxHeight: '15rem',
    overflowY: 'auto',
    px: 1,
  },
  '& .location-input > .MuiInputBase-root': {
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    px: 1.5,
    fontSize: FONT_SIZES.md,
    flexGrow: 1,
    '& input': {
      py: 1.5,
    },
    '& input::placeholder': {
      color: '#8A8271',
      opacity: 1,
    },
  },
  '& .location-input .MuiIconButton-root': {
    color: PALETTE_COLORS.pine,
  },
  '& .location-input > .MuiStack-root:last-of-type .MuiIconButton-root': {
    color: PALETTE_COLORS.neon_orange,
    '&:hover': {
      color: '#E0451A',
      backgroundColor: 'rgba(255,82,27,0.08)',
    },
  },
  '& .location-input > .MuiStack-root': {
    justifyContent: 'center',
  },
};

export const DemoVideoStyle: SxProps = {
  width: {
    xs: '92vw',
    md: '86vw',
    lg: '78vw',
  },
  mt: 3,
  mb: 2,
  alignItems: 'center',
  '& .demo-card': {
    width: '100%',
    borderRadius: 4,
    overflow: 'hidden',
    background: `radial-gradient(circle at 15% 0%, #1b2a3a 0%, ${PALETTE_COLORS.forest} 45%, #0a1410 100%)`,
    boxShadow: '0 24px 70px -24px rgba(0,0,0,0.55)',
  },
  '& .demo-topbar': {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    px: { xs: 2, md: 3 },
    py: 1.5,
  },
  '& .demo-badge': {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 1.5,
    py: 0.6,
    borderRadius: 999,
    background: 'rgba(255,82,27,0.14)',
    color: t => (t as Theme).palette.primary.light,
    fontWeight: 800,
    letterSpacing: '0.1em',
    fontSize: FONT_SIZES.xs,
    textTransform: 'uppercase',
    flexShrink: 0,
    '& .dot': {
      width: 8,
      height: 8,
      borderRadius: '50%',
      background: t => (t as Theme).palette.primary.main,
      boxShadow: '0 0 0 4px rgba(255,82,27,0.25)',
    },
  },
  '& .demo-topbar-title': {
    color: 'rgba(255,255,255,0.7)',
    fontWeight: 600,
    fontSize: FONT_SIZES.sm,
    textAlign: 'right',
    display: { xs: 'none', sm: 'block' },
  },
  '& .demo-player': {
    position: 'relative',
    width: '100%',
    aspectRatio: '16 / 9',
    overflow: 'hidden',
    background: '#0a1410',
    '& iframe, & video': {
      display: 'block',
    },
  },
};

export const BirdiaTechnologyStyle: SxProps = {
  width: {
    xs: '92vw',
    md: '86vw',
    lg: '78vw',
  },
  mt: 6,
  gap: 4,
  '& .section-header': {
    textAlign: 'center',
    gap: 1.5,
    '& .section-eyebrow': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
    },
    '& .section-title': {
      fontWeight: 800,
      lineHeight: 1.1,
      color: PALETTE_COLORS.black,
      fontSize: {
        xs: FONT_SIZES['2xl'],
        md: FONT_SIZES['4xl'],
      },
      '& .accent': {
        color: t => (t as Theme).palette.primary.main,
      },
    },
    '& .section-subtitle': {
      color: '#6B7280',
      maxWidth: 620,
      mx: 'auto',
      fontSize: {
        xs: FONT_SIZES.sm,
        md: FONT_SIZES.md,
      },
    },
  },
  '& .section-content': {
    display: 'flex',
    flexDirection: {
      xs: 'column',
      md: 'row',
    },
    alignItems: 'stretch',
    gap: 3,
    width: '100%',
  },
  '& .preview-card': {
    position: 'relative',
    overflow: 'hidden',
    flex: 1,
    aspectRatio: '16 / 9',
    minHeight: {
      xs: 0,
      md: 0,
    },
    borderRadius: 4,
    p: 3,
    background: `linear-gradient(to bottom, rgba(10,20,16,0.55) 0%, rgba(10,20,16,0.35) 45%, rgba(10,20,16,0.85) 100%), url(/assets/images/illustration.webp)`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    boxShadow: '0 20px 60px -20px rgba(0,0,0,0.45)',
    '& .corner': {
      position: 'absolute',
      width: 40,
      height: 40,
      borderColor: t => (t as Theme).palette.primary.main,
      borderStyle: 'solid',
      borderWidth: 0,
    },
    '& .corner-tr': {
      top: 20,
      right: 20,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopRightRadius: 8,
    },
    '& .corner-bl': {
      bottom: 120,
      left: 20,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomLeftRadius: 8,
    },
    '& .preview-label': {
      position: 'absolute',
      display: 'flex',
      alignItems: 'center',
      gap: 1,
      color: PALETTE_COLORS.white,
      fontWeight: 700,
      fontSize: FONT_SIZES.sm,
      zIndex: 1,
      '& .dot': {
        width: 10,
        height: 10,
        borderRadius: '50%',
        flexShrink: 0,
      },
    },
    '& .preview-label-usure': { top: 40, left: 30 },
    '& .preview-label-moisissure': { top: '20%', right: 40 },
    '& .preview-label-humide': { bottom: 150, left: '25%' },
    '& .preview-stats': {
      position: 'absolute',
      left: 24,
      right: 24,
      bottom: 24,
      display: 'grid',
      gridTemplateColumns: '1fr 1fr 1fr',
      gap: 1.5,
      '& .preview-stat': {
        borderRadius: 3,
        py: 2,
        px: 1,
        textAlign: 'center',
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.08)',
        '& .stat-value': {
          color: PALETTE_COLORS.white,
          fontWeight: 800,
          fontSize: FONT_SIZES.lg,
        },
        '& .stat-label': {
          color: 'rgba(255,255,255,0.55)',
          fontWeight: 600,
          letterSpacing: '0.08em',
          fontSize: FONT_SIZES.xs,
          textTransform: 'uppercase',
        },
      },
    },
  },
  '& .feature-list': {
    flex: 1,
    gap: 2,
  },
  '& .feature-card': {
    display: 'flex',
    gap: 2,
    p: 2.5,
    borderRadius: 4,
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .feature-icon': {
      flexShrink: 0,
      width: 52,
      height: 52,
      borderRadius: 3,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: FONT_SIZES['2xl'],
      background: PALETTE_COLORS.peach,
    },
    '& .feature-title': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.md,
    },
    '& .feature-desc': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
      my: 0.5,
    },
    '& .feature-tags': {
      flexWrap: 'wrap',
      gap: 1,
      mt: 1,
      '& .feature-tag': {
        px: 1.2,
        py: 0.4,
        borderRadius: 2,
        fontWeight: 700,
        fontSize: FONT_SIZES.xs,
        textTransform: 'uppercase',
        letterSpacing: '0.03em',
        background: '#F1F1F3',
        color: '#4B5563',
      },
      '& .feature-tag-blue': { background: '#E4EEFF', color: '#2563EB' },
      '& .feature-tag-green': { background: '#E4F7E9', color: '#2E9E52' },
      '& .feature-tag-orange': { background: '#FFEBDD', color: '#E0682B' },
    },
  },
};

export const ReportPreviewStyle: SxProps = {
  width: {
    xs: '92vw',
    md: '86vw',
    lg: '78vw',
  },
  mt: 6,
  gap: 4,
  '& .section-header': {
    textAlign: 'center',
    gap: 1.5,
    '& .section-eyebrow': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
    },
    '& .section-title': {
      fontWeight: 800,
      lineHeight: 1.1,
      color: PALETTE_COLORS.black,
      fontSize: {
        xs: FONT_SIZES['2xl'],
        md: FONT_SIZES['4xl'],
      },
    },
    '& .section-subtitle': {
      color: '#6B7280',
      maxWidth: 620,
      mx: 'auto',
      fontSize: {
        xs: FONT_SIZES.sm,
        md: FONT_SIZES.md,
      },
    },
  },
  '& .report-cards': {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: 'repeat(3, minmax(0, 1fr))',
    },
    gap: 3,
    width: '100%',
  },
  '& .report-card': {
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    borderRadius: 4,
    p: 3,
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .card-header': {
      alignItems: 'center',
      gap: 1.5,
      '& .card-icon': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: 2.5,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: FONT_SIZES.lg,
        background: PALETTE_COLORS.peach,
      },
      '& .card-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.lg,
      },
    },
    '& .card-divider': {
      my: 2,
      borderColor: '#EFEAE0',
    },
    '& .card-divider-dashed': {
      borderStyle: 'dashed',
    },
  },
  '& .identity-rows': {
    gap: 1.25,
    '& .identity-row': {
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 2,
    },
    '& .identity-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .identity-value': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
      textAlign: 'right',
    },
    '& .identity-value-highlight': {
      color: t => (t as Theme).palette.primary.main,
    },
  },
  '& .health-bars': {
    gap: 2,
    '& .health-bar-head': {
      justifyContent: 'space-between',
      alignItems: 'center',
      mb: 0.75,
    },
    '& .health-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .health-value': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
    },
    '& .health-value-alert': {
      color: t => (t as Theme).palette.primary.main,
    },
    '& .health-track': {
      width: '100%',
      height: 6,
      borderRadius: 999,
      background: '#F1F1F3',
      overflow: 'hidden',
      '& .health-fill': {
        height: '100%',
        borderRadius: 999,
        background: '#2E9E52',
      },
      '& .health-fill-alert': {
        background: t => (t as Theme).palette.primary.main,
      },
    },
  },
  '& .health-flags': {
    gap: 1.25,
    '& .health-flag': {
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    '& .flag-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .flag-value': {
      fontWeight: 800,
      color: '#2E9E52',
      fontSize: FONT_SIZES.sm,
    },
  },
  '& .degradation': {
    alignItems: 'center',
    textAlign: 'center',
    '& .degradation-rate': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      lineHeight: 1,
      fontSize: FONT_SIZES['5xl'],
      '& .degradation-unit': {
        fontSize: FONT_SIZES['2xl'],
        fontWeight: 800,
      },
    },
    '& .degradation-caption': {
      color: '#6B7280',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
      mt: 0.5,
    },
    '& .grade-scale': {
      width: '100%',
      gap: 0.75,
      mt: 2,
      '& .grade-box': {
        flex: 1,
        py: 1,
        borderRadius: 2,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 0.25,
        border: '2px solid transparent',
        '& .grade-letter': {
          fontWeight: 800,
          fontSize: FONT_SIZES.md,
        },
        '& .grade-label': {
          fontWeight: 700,
          letterSpacing: '0.02em',
          textTransform: 'uppercase',
          fontSize: '0.5rem',
        },
      },
      '& .grade-box-a': { background: '#E4F7E9', color: '#2E9E52' },
      '& .grade-box-b': { background: '#EAF7E2', color: '#5AA83C' },
      '& .grade-box-c': { background: '#FDF6DD', color: '#C99A1E' },
      '& .grade-box-d': { background: '#FFEBDD', color: '#E0682B' },
      '& .grade-box-e': { background: '#FCE4E4', color: '#D64545' },
      '& .grade-box-selected': {
        borderColor: t => (t as Theme).palette.primary.main,
        boxShadow: '0 8px 20px -10px rgba(255,82,27,0.5)',
        transform: 'scale(1.05)',
      },
    },
    '& .degradation-verdict': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      fontSize: FONT_SIZES.md,
    },
    '& .degradation-detail': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
      mt: 1,
    },
  },
  '& .advice-panel': {
    width: '100%',
    position: 'relative',
    borderRadius: 4,
    background: 'linear-gradient(180deg, #FFF7EF 0%, #FFF1E6 100%)',
    border: '1px solid #FBD9BE',
    '& .advice-header': {
      padding: 2,
      alignItems: 'center',
      gap: 1.5,
      mb: 3,
      '& .advice-header-icon': {
        fontSize: FONT_SIZES.xl,
      },
      '& .advice-header-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.lg,
      },
    },
    '& .advice-grid': {
      display: 'grid',
      padding: 2,
      gridTemplateColumns: {
        xs: '95%',
        md: '45% 45%',
      },
      gap: { xs: 2.5, md: 3 },
    },
    '& .advice-item': {
      gap: 1.5,
      alignItems: 'flex-start',
      '& .advice-icon': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: FONT_SIZES.md,
      },
      '& .advice-icon-search': { background: '#FDF3D8' },
      '& .advice-icon-broom': { background: '#E4F7E9' },
      '& .advice-icon-pick': { background: '#FCE0E0' },
      '& .advice-icon-calendar': { background: '#E4EEFF' },
      '& .advice-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.md,
      },
      '& .advice-desc': {
        color: '#6B7280',
        fontSize: FONT_SIZES.sm,
        mt: 0.5,
      },
    },
    '& .advice-disclaimer': {
      mt: 3,
      m: 2,
      p: 2,
      borderRadius: 3,
      textAlign: 'center',
      fontWeight: 700,
      fontSize: FONT_SIZES.sm,
      color: '#8A6D1B',
      background: '#FDF3D0',
      border: '1px solid #F6E4A8',
    },
  },
};

export const TestimonialsStyle: SxProps = {
  width: {
    xs: '92vw',
    md: '86vw',
    lg: '78vw',
  },
  mt: 6,
  mb: 4,
  gap: 4,
  '& .section-header': {
    flexDirection: {
      xs: 'column',
      md: 'row',
    },
    justifyContent: 'space-between',
    alignItems: {
      xs: 'flex-start',
      md: 'flex-end',
    },
    gap: 2,
    '& .section-heading': {
      gap: 1,
      '& .section-eyebrow': {
        color: t => (t as Theme).palette.primary.main,
        fontWeight: 800,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        fontSize: FONT_SIZES.xs,
      },
      '& .section-title': {
        fontWeight: 800,
        lineHeight: 1.1,
        color: PALETTE_COLORS.black,
        fontSize: {
          xs: FONT_SIZES['2xl'],
          md: FONT_SIZES['4xl'],
        },
      },
    },
    '& .rating-summary': {
      alignItems: 'center',
      gap: 1,
      flexShrink: 0,
      '& .rating-stars .star': {
        color: '#F5A623',
        fontSize: FONT_SIZES.lg,
        letterSpacing: '0.05em',
      },
      '& .rating-score': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.md,
      },
      '& .rating-count': {
        color: '#6B7280',
        fontSize: FONT_SIZES.sm,
      },
    },
  },
  '& .review-carousel': {
    width: '100%',
    overflow: 'hidden',
    py: 1,
    // Fade the edges so cards slide in/out smoothly.
    maskImage: 'linear-gradient(to right, transparent 0, #000 6%, #000 94%, transparent 100%)',
    WebkitMaskImage: 'linear-gradient(to right, transparent 0, #000 6%, #000 94%, transparent 100%)',
    '&:hover .review-track': {
      animationPlayState: 'paused',
    },
    '@keyframes review-marquee': {
      from: { transform: 'translateX(0)' },
      to: { transform: 'translateX(-50%)' },
    },
  },
  '& .review-track': {
    display: 'flex',
    width: 'max-content',
    gap: 3,
    animation: 'review-marquee 40s linear infinite',
  },
  '& .review-card': {
    flexShrink: 0,
    width: {
      xs: '80vw',
      sm: '340px',
    },
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    borderRadius: 4,
    p: 3,
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .review-mark': {
      color: t => (t as Theme).palette.primary.light,
      fontWeight: 800,
      lineHeight: 0.6,
      fontSize: FONT_SIZES['4xl'],
    },
    '& .review-stars': {
      mt: 1,
      '& .star': {
        color: '#F5A623',
        fontSize: FONT_SIZES.md,
        letterSpacing: '0.05em',
      },
    },
    '& .review-quote': {
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
      lineHeight: 1.5,
      mt: 1.5,
      flexGrow: 1,
    },
    '& .review-divider': {
      my: 2,
      borderColor: '#EFEAE0',
    },
    '& .review-author': {
      alignItems: 'center',
      gap: 1.5,
      '& .review-avatar': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 800,
        fontSize: FONT_SIZES.xs,
        color: PALETTE_COLORS.white,
        background: t => (t as Theme).palette.primary.main,
      },
      '& .review-name': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.sm,
      },
      '& .review-role': {
        color: '#6B7280',
        fontSize: FONT_SIZES.xs,
      },
    },
  },
  '& .trust-divider': {
    borderColor: '#EFEAE0',
    width: '100%',
  },
  '& .trust-badges': {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
    },
    gap: { xs: 2, md: 3 },
    width: '100%',
  },
  '& .trust-badge': {
    alignItems: 'center',
    gap: 1.5,
    justifyContent: { xs: 'flex-start', md: 'center' },
    '& .trust-icon': {
      flexShrink: 0,
      width: 44,
      height: 44,
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: FONT_SIZES.md,
    },
    '& .trust-icon-rgpd': { background: '#E4F7E9' },
    '& .trust-icon-ssl': { background: '#E4EEFF' },
    '& .trust-icon-rge': { background: '#FDF3D8' },
    '& .trust-icon-ia': { background: PALETTE_COLORS.peach },
    '& .trust-title': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
    },
    '& .trust-subtitle': {
      color: '#6B7280',
      fontSize: FONT_SIZES.xs,
    },
  },
  '& .trust-footer': {
    textAlign: 'center',
    color: '#6B7280',
    fontWeight: 600,
    fontSize: FONT_SIZES.sm,
  },
};

export const detectionResultItemStyle: SxProps = {
  border: `3px solid ${PALETTE_COLORS.pine}`,
  '& .detection-result-item-loading': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
  },
  '& .item-label-container': {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    position: 'relative',
    '& .MuiTypography-root': {
      textAlign: 'center',
      fontWeight: 'bold',
    },
    '& .color-legend': {
      position: 'absolute',
      left: 1,
      top: '50%',
      transform: 'translateY(-50%)',
      height: 20,
      width: 20,
      border: `2px solid ${PALETTE_COLORS.pine}`,
      borderRadius: '2px',
    },
  },
};
