import { FONT_SIZES, PALETTE_COLORS } from '@/utilities/theme';
import { SxProps, Theme } from '@mui/material';

/**
 * Reference palette for the redesigned landing page (60/30/10 cream / white / orange).
 * Kept local to the landing styles so the rest of the app keeps using the MUI theme.
 */
const REF = {
  bg: '#F5EFE2',
  card: '#FFFFFF',
  dark: '#17181B',
  orange: '#E96B33',
  orangeDark: '#C95822',
  orangeSoft: '#FBE6D8',
  text: '#17181B',
  textMuted: '#6B6B6B',
  textSoft: '#4A4A4A',
  border: '#E8DFC9',
  borderStrong: '#D5CBB2',
  shadowSm: '0 2px 8px rgba(31, 24, 12, 0.04)',
  shadow: '0 10px 32px rgba(31, 24, 12, 0.08)',
  shadowLg: '0 20px 50px rgba(31, 24, 12, 0.14)',
  radius: '20px',
  radiusSm: '12px',
};

export const DetectionResultStepStyle: SxProps = {
  position: 'relative',
  mb: 10,
  p: 1,
  width: {
    xs: '97vw',
    sm: '95vw',
    md: '94vw',
    lg: '92vw',
  },
  minHeight: '600px',
  height: 'fit-content',
  display: 'flex',
  alignItems: 'flex-start',
  flexWrap: 'wrap',
  '& .MuiGrid2-root > .title': {
    fontSize: {
      xs: FONT_SIZES.md,
      sm: FONT_SIZES.lg,
      md: FONT_SIZES.xl,
      lg: FONT_SIZES['2xl'],
    },
  },
  '& .MuiGrid2-root > .MuiPaper-root > .MuiTypography-root.label': {
    fontSize: {
      xs: FONT_SIZES.sm,
      sm: FONT_SIZES.md,
      md: FONT_SIZES.lg,
      lg: FONT_SIZES.xl,
    },
    textTransform: 'lowercase',
  },
  '& .MuiGrid2-root > .MuiPaper-root > .MuiTypography-root.result': {
    fontSize: {
      xs: FONT_SIZES.sm,
      sm: FONT_SIZES.md,
      md: FONT_SIZES.lg,
      lg: FONT_SIZES.xl,
    },
    textTransform: 'capitalize',
  },
  '& .analyse-result-info': {
    '& .title': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 'bold',
      fontSize: FONT_SIZES.xl,
      textAlign: 'center',
    },
    p: 2,
    borderRadius: 5,
    boxShadow: `0.4px 0.4px 2.2px -8px rgba(0, 0, 0, 0.02), 1px 1px 5.3px -8px rgba(0, 0, 0, 0.028), 1.9px 1.9px 10px -8px rgba(0, 0, 0, 0.035), 3.4px 3.4px 17.9px -8px rgba(0, 0, 0, 0.042), 6.3px 6.3px 33.4px -8px rgba(0, 0, 0, 0.05), 15px 15px 80px -8px rgba(0, 0, 0, 0.07)`,
  },
  '& .MuiPaper-root': {
    p: 1,
    my: 1,
    display: 'flex',
    alignItems: 'center',
    boxShadow: 'none',
  },
  gap: 1,
  '& .degradation-switch': {
    py: 2,
    display: 'flex',
    justifyContent: { xs: 'center', md: 'flex-start' },
    width: '100%',
  },
  '& .roof-state': {
    width: '100%',
    scrollMarginTop: { xs: 24, md: 48 },
    my: { xs: 3, md: 4 },
    borderRadius: 4,
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& > *': {
      mx: { xs: 2, md: 3 },
      my: { xs: 1, md: 1.5 },
    },
    '& .roof-state-title': {
      fontWeight: 800,
      textTransform: 'uppercase',
      letterSpacing: '0.02em',
      color: PALETTE_COLORS.forest,
      fontSize: {
        xs: FONT_SIZES.md,
        md: FONT_SIZES.xl,
      },
    },
    '& .roof-state-divider': {
      my: 1,
      borderColor: '#EFEAE0',
    },
    '& .roof-state-cards': {
      display: 'grid',
      gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', sm: 'repeat(5, minmax(0, 1fr))' },
      gap: { xs: 1, md: 1.5 },
      alignItems: 'stretch',
    },
    '& .roof-state-card': {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      gap: 0.5,
      px: { xs: 0.5, md: 1 },
      py: 1,
      borderRadius: 3,
      border: '2px solid transparent',
      transition: 'all 300ms',
      '& .roof-state-icon': {
        width: { xs: 36, md: 44 },
        height: { xs: 36, md: 44 },
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: { xs: FONT_SIZES.lg, md: FONT_SIZES['2xl'] },
      },
      '& .roof-state-card-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.forest,
        lineHeight: 1.15,
        fontSize: { xs: FONT_SIZES.xs, md: FONT_SIZES.sm },
      },
      '& .roof-state-card-desc': {
        color: '#9AA1AC',
        lineHeight: 1.2,
        fontSize: { xs: '0.65rem', md: FONT_SIZES.xs },
      },
    },
    '& .roof-state-card-good .roof-state-icon': { background: '#E4F7E9', color: '#2E9E52' },
    '& .roof-state-card-preventive .roof-state-icon': { background: '#EAF7E2', color: '#5AA83C' },
    '& .roof-state-card-maintenance .roof-state-icon': { background: '#FDF6DD', color: '#C99A1E' },
    '& .roof-state-card-repair .roof-state-icon': { background: '#FFEBDD', color: '#E0682B' },
    '& .roof-state-card-critical .roof-state-icon': { background: '#FCE4E4', color: '#D64545' },
    '& .roof-state-card-selected': {
      borderColor: PALETTE_COLORS.forest,
      boxShadow: '0 12px 28px -16px rgba(17,39,23,0.6)',
    },
    '& .roof-state-meter': {
      display: 'grid',
      gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
      gap: { xs: 0.75, md: 1.5 },
      mt: 1,
      '& .roof-state-meter-col': {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 0.5,
        '& .roof-state-meter-bar': {
          width: '100%',
          height: 8,
          borderRadius: 999,
        },
        '& .roof-state-meter-dot': {
          width: 8,
          height: 8,
          borderRadius: '50%',
          background: '#C7CBD1',
        },
        '& .roof-state-meter-pointer': {
          width: 0,
          height: 0,
          borderLeft: '6px solid transparent',
          borderRight: '6px solid transparent',
          borderBottom: `8px solid ${PALETTE_COLORS.forest}`,
        },
      },
      '& .roof-state-meter-bar-good': { background: '#47BE62' },
      '& .roof-state-meter-bar-preventive': { background: '#8CC63F' },
      '& .roof-state-meter-bar-maintenance': { background: '#F5CE3E' },
      '& .roof-state-meter-bar-repair': { background: '#F0883E' },
      '& .roof-state-meter-bar-critical': { background: '#EF4444' },
    },
    '& .roof-state-summary': {
      mt: 1.5,
      p: { xs: 1.25, md: 1.5 },
      borderRadius: 3,
      background: '#F5F6F7',
      display: 'flex',
      flexDirection: { xs: 'column', sm: 'row' },
      alignItems: { xs: 'flex-start', sm: 'center' },
      gap: { xs: 1, sm: 1.5 },
      '& .roof-state-summary-level': {
        display: 'flex',
        alignItems: 'center',
        gap: 1,
        flex: 1,
      },
      '& .roof-state-summary-icon': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: FONT_SIZES.lg,
      },
      '& .roof-state-summary-label': {
        color: '#9AA1AC',
        fontWeight: 700,
        letterSpacing: '0.06em',
        textTransform: 'uppercase',
        fontSize: FONT_SIZES.xs,
      },
      '& .roof-state-summary-verdict': {
        fontWeight: 800,
        lineHeight: 1.15,
        mt: 0.25,
        fontSize: { xs: FONT_SIZES.md, md: FONT_SIZES.lg },
      },
      '& .roof-state-summary-divider': {
        borderColor: '#DDE0E3',
        display: { xs: 'none', sm: 'block' },
      },
      '& .roof-state-summary-score': {
        flexShrink: 0,
      },
      '& .roof-state-summary-value': {
        fontWeight: 800,
        lineHeight: 1,
        mt: 0.25,
        fontSize: { xs: FONT_SIZES.xl, md: FONT_SIZES['2xl'] },
      },
    },
    '& .roof-state-footnote': {
      color: '#9AA1AC',
      fontSize: FONT_SIZES.xs,
      mt: 1,
    },
  },
  '& .roof-state-good': {
    '& .roof-state-summary-icon': { background: '#E4F7E9', color: '#2E9E52' },
    '& .roof-state-summary-verdict, & .roof-state-summary-value': { color: '#2E9E52' },
  },
  '& .roof-state-preventive': {
    '& .roof-state-summary-icon': { background: '#EAF7E2', color: '#5AA83C' },
    '& .roof-state-summary-verdict, & .roof-state-summary-value': { color: '#5AA83C' },
  },
  '& .roof-state-maintenance': {
    '& .roof-state-summary-icon': { background: '#FDF6DD', color: '#C99A1E' },
    '& .roof-state-summary-verdict, & .roof-state-summary-value': { color: '#C99A1E' },
  },
  '& .roof-state-repair': {
    '& .roof-state-summary-icon': { background: '#FFEBDD', color: '#E0682B' },
    '& .roof-state-summary-verdict, & .roof-state-summary-value': { color: '#E0682B' },
  },
  '& .roof-state-critical': {
    '& .roof-state-summary-icon': { background: '#FCE4E4', color: '#D64545' },
    '& .roof-state-summary-verdict, & .roof-state-summary-value': { color: '#D64545' },
  },
  '& .disclaimer-container': {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
};

export const GetAddressStepStyle: SxProps = {
  width: '100%',
  color: REF.text,

  // ---- shared section wrappers (centered, capped) ----
  '& .landing-hero, & .landing-trust, & .landing-howto, & .landing-carousel': {
    width: { xs: '97vw', md: '94vw', lg: '92vw' },
    maxWidth: 1380,
    mx: 'auto',
  },
  '& .landing-howto, & .landing-carousel': {
    py: { xs: 5, md: 8 },
  },
  '& .landing-trust': {
    pt: { xs: 3, md: 4 },
  },

  // ---- trust strip (key stats) ----
  '& .trust-strip': {
    maxWidth: 1180,
    mx: 'auto',
    display: 'grid',
    gridTemplateColumns: { xs: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' },
    borderRadius: REF.radius,
    overflow: 'hidden',
    background: `radial-gradient(circle at 20% 20%, #1b2a3a 0%, ${PALETTE_COLORS.forest} 55%, #0a1410 100%)`,
    boxShadow: '0 12px 40px -12px rgba(0,0,0,0.35)',
  },
  '& .trust-cell': {
    textAlign: 'center',
    color: REF.card,
    py: { xs: 2, md: 2.75 },
    px: 2,
    borderRight: { md: '1px solid rgba(255,255,255,0.08)' },
    '&:last-of-type': { borderRight: 0 },
  },
  '& .trust-val': {
    color: REF.card,
    fontWeight: 900,
    fontSize: { xs: FONT_SIZES.xl, md: FONT_SIZES['2xl'] },
    letterSpacing: '-0.02em',
    lineHeight: 1,
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 0.5,
    '& span': { color: REF.orange, fontSize: '0.75em' },
  },
  '& .trust-label': {
    fontSize: FONT_SIZES.xs,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    mt: 1,
  },
  // hero nav + split use the reference index.html container width (max-width: 1140px; padding: 0 24px)
  '& .landing-hero .top-nav, & .landing-hero .hero-split': {
    width: '100%',
    maxWidth: 1140,
    mx: 'auto',
    px: 3,
  },

  // ---- shared accent + section heads ----
  '& .accent': { color: REF.orange },
  '& .section-head': {
    textAlign: 'center',
    mb: 4,
    '& .section-head-title': {
      fontWeight: 700,
      letterSpacing: '-0.015em',
      lineHeight: 1.2,
      color: REF.text,
      fontSize: { xs: FONT_SIZES['2xl'], md: FONT_SIZES['3xl'] },
    },
    '& .section-head-sub': {
      mt: 1.5,
      color: REF.textMuted,
      fontSize: FONT_SIZES.sm,
      maxWidth: 520,
      mx: 'auto',
    },
  },

  // ---- top nav ----
  '& .top-nav': {
    pt: 3,
    pb: 1,
    display: 'flex',
    justifyContent: 'flex-end',
    '& .header-birdia': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 1,
      fontSize: FONT_SIZES.xs,
      color: REF.textMuted,
      letterSpacing: '0.05em',
      '& strong': { color: REF.textSoft, fontWeight: 600, ml: '2px' },
      '& .dot': { width: 6, height: 6, borderRadius: '50%', background: REF.orange },
    },
  },

  // ---- hero split ----
  '& .hero-split': {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '300px 1fr' },
    gap: { xs: 3, md: 6 },
    alignItems: 'center',
    py: { xs: 2, md: 4 },
  },
  '& .partner-card': {
    background: REF.card,
    border: `1px solid ${REF.border}`,
    borderRadius: REF.radius,
    boxShadow: REF.shadow,
    maxWidth: { xs: 380, md: 'none' },
    mx: { xs: 'auto', md: 0 },
    width: '100%',
    padding: 3,
    '& .partner-card-logo': {
      width: '100%',
      aspectRatio: '4 / 3',
      borderRadius: REF.radiusSm,
      background: '#fff',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      mb: 2.25,
      overflow: 'hidden',
      '& img': { maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' },
    },
    '& .partner-name': { fontSize: FONT_SIZES.lg, fontWeight: 800, color: REF.text, mb: 0.75 },
    '& .partner-addr': {
      fontSize: FONT_SIZES.xs,
      fontWeight: 600,
      color: REF.textSoft,
      lineHeight: 1.5,
      mb: 1.25,
      '& a': { color: 'inherit', textDecoration: 'none' },
      '& a:hover': { color: REF.orange },
    },
    '& .partner-contact': {
      fontSize: FONT_SIZES.xs,
      color: REF.textMuted,
      lineHeight: 1.6,
      pt: 1.5,
      borderTop: `1px dashed ${REF.borderStrong}`,
      '& a': { color: 'inherit', textDecoration: 'none' },
      '& a:hover': { color: REF.orange },
      '& strong': { color: REF.text, fontWeight: 600 },
    },
  },
  '& .hero-content': {
    textAlign: 'center',
    alignItems: 'center',
    '& .hero-title': {
      fontWeight: 800,
      lineHeight: 1.05,
      letterSpacing: '-0.025em',
      color: REF.text,
      maxWidth: 640,
      mb: 2.25,
      fontSize: { xs: '2.375rem', md: '3.75rem' },
    },
    '& .hero-lead': { fontSize: FONT_SIZES.lg, color: REF.textMuted, maxWidth: 560, mb: 3.5, lineHeight: 1.55 },
    '& .hero-note': { mt: 2.5, fontSize: FONT_SIZES.sm, color: REF.textMuted, '& strong': { color: REF.text, fontWeight: 600 } },
  },

  // ---- FR badge ----
  '& .fr-badge': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    py: '7px',
    px: '14px',
    pl: 1,
    background: '#fff',
    border: `1.5px solid ${REF.border}`,
    borderRadius: 999,
    fontSize: FONT_SIZES.xs,
    fontWeight: 600,
    color: REF.text,
    boxShadow: REF.shadowSm,
    lineHeight: 1,
    whiteSpace: 'nowrap',
    mb: 2.5,
    '& em': { fontStyle: 'normal', fontWeight: 500, color: REF.textMuted },
  },
  '& .fr-flag': {
    display: 'inline-flex',
    alignItems: 'center',
    width: 22,
    height: 16,
    borderRadius: '3px',
    overflow: 'hidden',
    boxShadow: '0 0 0 1px rgba(0,0,0,0.08)',
    flexShrink: 0,
    '& span': { display: 'block', height: '100%', flex: 1 },
    '& .fr-blue': { background: '#002395' },
    '& .fr-white': { background: '#FFFFFF' },
    '& .fr-red': { background: '#ED2939' },
  },

  // ---- address form (shared by hero + CTAs) ----
  '& .address-search': { width: '100%', maxWidth: 620, mx: 'auto', position: 'relative' },
  '& .address-form': {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    p: '8px',
    pl: '22px',
    width: '100%',
    background: REF.card,
    border: `1.5px solid ${REF.borderStrong}`,
    borderRadius: 999,
    boxShadow: REF.shadow,
    transition: 'border-color 0.15s, box-shadow 0.15s',
    flexDirection: { xs: 'column', sm: 'row' },
    '&:focus-within': { borderColor: REF.orange, boxShadow: `0 0 0 4px rgba(233, 107, 51, 0.12), ${REF.shadow}` },
  },
  '& .address-form-pin': { color: REF.textMuted, flexShrink: 0, display: { xs: 'none', sm: 'block' } },
  '& .address-form-input': {
    flex: 1,
    width: '100%',
    fontSize: FONT_SIZES.md,
    color: REF.text,
    '& input': { py: 1.75, px: 1 },
    '& input::placeholder': { color: REF.textMuted, opacity: 1 },
  },
  '& .btn-primary': {
    flexShrink: 0,
    background: REF.orange,
    color: '#fff',
    fontWeight: 700,
    fontSize: FONT_SIZES.sm,
    py: 1.75,
    px: 3.25,
    borderRadius: 999,
    textTransform: 'none',
    boxShadow: 'none',
    whiteSpace: 'nowrap',
    width: { xs: '100%', sm: 'auto' },
    transition: 'background 0.15s, transform 0.15s',
    '&:hover': { background: REF.orangeDark, transform: 'translateY(-1px)', boxShadow: 'none' },
    '& .MuiSvgIcon-root': { color: '#fff', fontSize: FONT_SIZES.md },
  },
  '& .address-list': {
    position: 'absolute',
    zIndex: 5,
    mt: 1,
    width: '100%',
    maxHeight: '15rem',
    overflowY: 'auto',
    '& .MuiPaper-root': { borderRadius: REF.radiusSm, border: `1px solid ${REF.border}`, boxShadow: REF.shadow },
  },

  // ---- how it works steps ----
  '& .steps': {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(5, 1fr)' },
    gap: { xs: 2, sm: 2.5, md: 2 },
    maxWidth: 1280,
    mx: 'auto',
    '&::before': {
      content: '""',
      position: 'absolute',
      display: { xs: 'none', md: 'block' },
      top: 22,
      left: 80,
      right: 80,
      height: 2,
      background: REF.border,
      zIndex: 0,
    },
  },
  '& .step': {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: 0.5,
    px: 1,
    '& .step-num': {
      width: 44,
      height: 44,
      background: REF.card,
      border: '2px solid rgba(31, 39, 55, 0.12)',
      borderRadius: '50%',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontWeight: 800,
      fontSize: FONT_SIZES.md,
      color: '#9aa2ad',
      transition: 'all 200ms linear',
      mb: 1,
    },
    '& .step-title': { fontWeight: 700, fontSize: FONT_SIZES.sm, color: REF.text, mt: 0.5, lineHeight: 1.3 },
    '& .step-subtitle': { fontWeight: 700, fontSize: FONT_SIZES.xs, color: REF.text },
    '& .step-desc': { fontSize: FONT_SIZES.xs, color: REF.textMuted, lineHeight: 1.4 },
  },
  '& .step.active .step-num': {
    background: REF.orange,
    borderColor: REF.orange,
    color: '#fff',
    boxShadow: '0 8px 20px -8px rgba(233, 107, 51, 0.6)',
  },

  // ---- inline CTA ----
  '& .cta-inline': {
    maxWidth: 780,
    mx: 'auto',
    mt: 4,
    background: REF.card,
    border: `1px solid ${REF.border}`,
    borderRadius: REF.radius,
    p: { xs: 3, md: '24px 28px' },
    textAlign: 'center',
    alignItems: 'center',
    boxShadow: REF.shadowSm,
    '& .cta-inline-title': { fontSize: FONT_SIZES.xl, fontWeight: 700, mb: 0.75 },
    '& .cta-inline-sub': { fontSize: FONT_SIZES.sm, color: REF.textMuted, mb: 2.5 },
  },

  // ---- PDF carousel ----
  '& .pdf-viewer': {
    maxWidth: 780,
    mx: 'auto',
    background: REF.card,
    border: `1px solid ${REF.border}`,
    borderRadius: REF.radius,
    p: { xs: 1.5, md: 2.5 },
    boxShadow: REF.shadow,
  },
  '& .pdf-stage': {
    position: 'relative',
    background: '#F0EBDD',
    borderRadius: REF.radiusSm,
    aspectRatio: '3 / 4',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& img': { maxWidth: '100%', height: '100%', width: 'auto', objectFit: 'contain', boxShadow: '0 8px 24px rgba(0,0,0,0.12)' },
  },
  '& .pdf-controls': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    mt: 2,
    flexWrap: 'wrap',
  },
  '& .pdf-btn': {
    background: REF.card,
    border: `1.5px solid ${REF.borderStrong}`,
    borderRadius: 999,
    py: 1.25,
    px: 2.25,
    fontSize: FONT_SIZES.sm,
    fontWeight: 600,
    color: REF.text,
    textTransform: 'none',
    boxShadow: 'none',
    '&:hover': { borderColor: REF.orange, color: REF.orange, background: REF.card, boxShadow: 'none' },
    '&:hover .MuiSvgIcon-root': { color: REF.orange },
    '&.Mui-disabled': { opacity: 0.4 },
    '& .MuiSvgIcon-root': { color: REF.text, fontSize: FONT_SIZES.md },
  },
  '& .pdf-counter': { fontSize: FONT_SIZES.sm, color: REF.textMuted, fontWeight: 600, '& strong': { color: REF.text, fontWeight: 800 } },
  '& .pdf-dots': {
    display: 'flex',
    gap: 0.5,
    flexWrap: 'wrap',
    justifyContent: 'center',
    mt: 1.5,
    '& button': {
      width: 8,
      height: 8,
      p: 0,
      border: 'none',
      background: REF.border,
      borderRadius: '50%',
      cursor: 'pointer',
      transition: 'background 0.15s, transform 0.15s',
      '&:hover': { background: REF.borderStrong },
      '&.active': { background: REF.orange, transform: 'scale(1.4)' },
    },
  },

  // ---- final CTA ----
  '& .cta-final': {
    width: { xs: '97vw', md: '94vw', lg: '92vw' },
    maxWidth: 920,
    mx: 'auto',
    mt: { xs: 4, md: 6 },
    background: 'linear-gradient(135deg, #FFF6EA 0%, #F5EFE2 100%)',
    border: `1.5px solid ${REF.orangeSoft}`,
    borderRadius: REF.radius,
    p: { xs: 3.5, md: '36px 32px' },
    textAlign: 'center',
    alignItems: 'center',
    '& .cta-final-title': { fontWeight: 700, fontSize: { xs: FONT_SIZES['2xl'], md: FONT_SIZES['3xl'] }, mb: 1.25 },
    '& .cta-final-sub': { fontSize: FONT_SIZES.md, color: REF.textMuted, mb: 3.5, maxWidth: 520 },
    '& .cta-final-note': { mt: 2, fontSize: FONT_SIZES.xs, color: REF.textMuted, '& strong': { color: REF.text, fontWeight: 600 } },
  },

  // ---- footer + trust ----
  '& .landing-footer': { width: { xs: '97vw', md: '94vw', lg: '92vw' }, maxWidth: 1180, mx: 'auto', mt: { xs: 5, md: 8 } },
  '& .trust': {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: { xs: 3, md: 6 },
    flexWrap: 'wrap',
    py: 5,
    borderTop: `1px solid ${REF.border}`,
    borderBottom: `1px solid ${REF.border}`,
    '& .trust-item': {
      display: 'flex',
      alignItems: 'center',
      gap: 1.25,
      fontSize: FONT_SIZES.sm,
      color: REF.textSoft,
      '& .MuiSvgIcon-root': { color: REF.textMuted, fontSize: FONT_SIZES.lg },
      '& strong': { fontWeight: 700 },
    },
  },
  '& .foot': {
    py: 4,
    textAlign: 'center',
    color: REF.textMuted,
    fontSize: FONT_SIZES.sm,
    '& .legal': { fontSize: FONT_SIZES.xs, opacity: 0.7, '& a': { textDecoration: 'underline', color: 'inherit' } },
  },
};

export const DemoVideoStyle: SxProps = {
  width: {
    xs: '97vw',
    md: '94vw',
    lg: '92vw',
  },
  maxWidth: 1100,
  mt: 6,
  gap: 4,
  alignItems: 'center',
  '& .section-header': {
    textAlign: 'center',
    gap: 1.5,
    '& .section-eyebrow': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
    },
    '& .section-title': {
      fontWeight: 800,
      lineHeight: 1.1,
      color: PALETTE_COLORS.black,
      fontSize: {
        xs: FONT_SIZES['2xl'],
        md: FONT_SIZES['4xl'],
      },
      '& .accent': {
        color: t => (t as Theme).palette.primary.main,
      },
    },
    '& .section-subtitle': {
      color: '#6B7280',
      maxWidth: 620,
      mx: 'auto',
      fontSize: {
        xs: FONT_SIZES.sm,
        md: FONT_SIZES.md,
      },
    },
  },
  '& .demo-card': {
    width: '100%',
    borderRadius: 4,
    overflow: 'hidden',
    background: `radial-gradient(circle at 15% 0%, #1b2a3a 0%, ${PALETTE_COLORS.forest} 45%, #0a1410 100%)`,
    boxShadow: '0 24px 70px -24px rgba(0,0,0,0.55)',
  },
  '& .demo-topbar': {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    px: { xs: 2, md: 3 },
    py: 1.5,
  },
  '& .demo-badge': {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 1.5,
    py: 0.6,
    borderRadius: 999,
    background: 'rgba(255,82,27,0.14)',
    color: t => (t as Theme).palette.primary.light,
    fontWeight: 800,
    letterSpacing: '0.1em',
    fontSize: FONT_SIZES.xs,
    textTransform: 'uppercase',
    flexShrink: 0,
    '& .dot': {
      width: 8,
      height: 8,
      borderRadius: '50%',
      background: t => (t as Theme).palette.primary.main,
      boxShadow: '0 0 0 4px rgba(255,82,27,0.25)',
    },
  },
  '& .demo-topbar-title': {
    color: 'rgba(255,255,255,0.7)',
    fontWeight: 600,
    fontSize: FONT_SIZES.sm,
    textAlign: 'right',
    display: { xs: 'none', sm: 'block' },
  },
  '& .demo-player': {
    position: 'relative',
    width: '100%',
    aspectRatio: { xs: '16 / 9', md: '2.75 / 1' },
    overflow: 'hidden',
    background: '#0a1410',
    '& iframe, & video': {
      display: 'block',
    },
  },
};

export const BirdiaTechnologyStyle: SxProps = {
  width: {
    xs: '97vw',
    md: '94vw',
    lg: '92vw',
  },
  maxWidth: 1180,
  mt: 6,
  gap: 4,
  '& .section-header': {
    textAlign: 'center',
    gap: 1.5,
    '& .section-eyebrow': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
    },
    '& .section-title': {
      fontWeight: 800,
      lineHeight: 1.1,
      color: PALETTE_COLORS.black,
      fontSize: {
        xs: FONT_SIZES['2xl'],
        md: FONT_SIZES['4xl'],
      },
      '& .accent': {
        color: t => (t as Theme).palette.primary.main,
      },
    },
    '& .section-subtitle': {
      color: '#6B7280',
      maxWidth: 620,
      mx: 'auto',
      fontSize: {
        xs: FONT_SIZES.sm,
        md: FONT_SIZES.md,
      },
    },
  },
  '& .section-content': {
    display: 'flex',
    flexDirection: {
      xs: 'column',
      md: 'row',
    },
    alignItems: 'stretch',
    gap: 3,
    width: '100%',
  },
  '& .preview-card': {
    position: 'relative',
    overflow: 'hidden',
    flex: 1,
    aspectRatio: '16 / 9',
    minHeight: {
      xs: 0,
      md: 0,
    },
    borderRadius: 4,
    p: 3,
    background: `linear-gradient(to bottom, rgba(10,20,16,0.55) 0%, rgba(10,20,16,0.35) 45%, rgba(10,20,16,0.85) 100%), url(/assets/images/landing/tech-preview.jpg)`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    boxShadow: '0 20px 60px -20px rgba(0,0,0,0.45)',
    '& .preview-label': {
      position: 'absolute',
      display: 'flex',
      alignItems: 'center',
      gap: 1,
      color: PALETTE_COLORS.white,
      fontWeight: 700,
      fontSize: FONT_SIZES.sm,
      zIndex: 1,
      '& .dot': {
        width: 10,
        height: 10,
        borderRadius: '50%',
        flexShrink: 0,
      },
    },
    '& .preview-label-usure': { top: 40, left: 30 },
    '& .preview-label-moisissure': { top: '20%', right: 40 },
    '& .preview-label-humide': { bottom: 40, left: '25%' },
  },
  '& .feature-list': {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  '& .feature-card': {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    p: 2.5,
    borderRadius: 4,
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .feature-icon': {
      flexShrink: 0,
      width: 52,
      height: 52,
      borderRadius: 3,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: FONT_SIZES['2xl'],
      background: PALETTE_COLORS.peach,
      color: PALETTE_COLORS.neon_orange,
    },
    '& .feature-title': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.md,
    },
    '& .feature-desc': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
      my: 0.5,
    },
    '& .feature-tags': {
      flexWrap: 'wrap',
      gap: 1,
      mt: 1,
      '& .feature-tag': {
        px: 1.2,
        py: 0.4,
        borderRadius: 2,
        fontWeight: 700,
        fontSize: FONT_SIZES.xs,
        textTransform: 'uppercase',
        letterSpacing: '0.03em',
        background: '#F1F1F3',
        color: '#4B5563',
      },
      '& .feature-tag-blue': { background: '#E4EEFF', color: '#2563EB' },
      '& .feature-tag-green': { background: '#E4F7E9', color: '#2E9E52' },
      '& .feature-tag-orange': { background: '#FFEBDD', color: '#E0682B' },
    },
  },
};

export const ReportPreviewStyle: SxProps = {
  width: {
    xs: '97vw',
    md: '94vw',
    lg: '92vw',
  },
  maxWidth: 1180,
  mt: 6,
  gap: 4,
  '& .section-header': {
    textAlign: 'center',
    gap: 1.5,
    '& .section-eyebrow': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
    },
    '& .section-title': {
      fontWeight: 800,
      lineHeight: 1.1,
      color: PALETTE_COLORS.black,
      fontSize: {
        xs: FONT_SIZES['2xl'],
        md: FONT_SIZES['4xl'],
      },
    },
    '& .section-subtitle': {
      color: '#6B7280',
      maxWidth: 620,
      mx: 'auto',
      fontSize: {
        xs: FONT_SIZES.sm,
        md: FONT_SIZES.md,
      },
    },
  },
  '& .report-cards': {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: 'repeat(3, minmax(0, 1fr))',
    },
    gap: 3,
    width: '100%',
  },
  '& .report-card': {
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    borderRadius: 4,
    p: 3,
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .card-header': {
      alignItems: 'center',
      gap: 1.5,
      '& .card-icon': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: 2.5,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: FONT_SIZES.lg,
        background: PALETTE_COLORS.peach,
        color: PALETTE_COLORS.neon_orange,
      },
      '& .card-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.lg,
      },
    },
    '& .card-divider': {
      my: 2,
      borderColor: '#EFEAE0',
    },
    '& .card-divider-dashed': {
      borderStyle: 'dashed',
    },
  },
  '& .identity-rows': {
    gap: 1.25,
    '& .identity-row': {
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 2,
    },
    '& .identity-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .identity-value': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
      textAlign: 'right',
    },
    '& .identity-value-highlight': {
      color: t => (t as Theme).palette.primary.main,
    },
    '& .identity-value-unavailable': {
      fontWeight: 600,
      fontStyle: 'italic',
      color: '#9AA1AC',
    },
  },
  '& .health-bars': {
    gap: 2,
    '& .health-bar-head': {
      justifyContent: 'space-between',
      alignItems: 'center',
      mb: 0.75,
    },
    '& .health-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .health-value': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
    },
    '& .health-value-alert': {
      color: t => (t as Theme).palette.primary.main,
    },
    '& .health-track': {
      width: '100%',
      height: 6,
      borderRadius: 999,
      background: '#F1F1F3',
      overflow: 'hidden',
      '& .health-fill': {
        height: '100%',
        borderRadius: 999,
        background: '#2E9E52',
      },
      '& .health-fill-alert': {
        background: t => (t as Theme).palette.primary.main,
      },
    },
  },
  '& .health-flags': {
    gap: 1.25,
    '& .health-flag': {
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    '& .flag-label': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
    },
    '& .flag-value': {
      fontWeight: 800,
      color: '#9AA1AC',
      fontSize: FONT_SIZES.sm,
    },
  },
  '& .degradation': {
    alignItems: 'center',
    textAlign: 'center',
    '& .degradation-rate': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      lineHeight: 1,
      fontSize: FONT_SIZES['5xl'],
      '& .degradation-unit': {
        fontSize: FONT_SIZES['2xl'],
        fontWeight: 800,
      },
    },
    '& .degradation-caption': {
      color: '#6B7280',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      fontSize: FONT_SIZES.xs,
      mt: 0.5,
    },
    '& .grade-scale': {
      width: '100%',
      mt: 2,
      '& .grade-cards': {
        display: 'grid',
        gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
        gap: 0.5,
        alignItems: 'stretch',
        '& .grade-card': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          textAlign: 'center',
          gap: 0.5,
          px: 0.25,
          py: 1,
          borderRadius: 2,
          border: '1.5px solid transparent',
          '& .grade-icon': {
            width: 34,
            height: 34,
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: FONT_SIZES.lg,
          },
          '& .grade-title': {
            fontWeight: 800,
            color: PALETTE_COLORS.black,
            lineHeight: 1.15,
            fontSize: '0.6rem',
          },
          '& .grade-desc': {
            color: '#9AA1AC',
            lineHeight: 1.2,
            fontSize: '0.5rem',
          },
        },
        '& .grade-card-good .grade-icon': { background: '#E4F7E9', color: '#2E9E52' },
        '& .grade-card-preventive .grade-icon': { background: '#EAF7E2', color: '#5AA83C' },
        '& .grade-card-maintenance .grade-icon': { background: '#FDF6DD', color: '#C99A1E' },
        '& .grade-card-repair .grade-icon': { background: '#FFEBDD', color: '#E0682B' },
        '& .grade-card-critical .grade-icon': { background: '#FCE4E4', color: '#D64545' },
        '& .grade-card-selected': {
          borderColor: t => (t as Theme).palette.primary.main,
          boxShadow: '0 8px 20px -12px rgba(255,82,27,0.5)',
        },
      },
      '& .grade-meter': {
        display: 'grid',
        gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
        gap: 0.75,
        mt: 1,
        px: 0.25,
        '& .grade-meter-col': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 0.5,
          '& .grade-meter-bar': {
            width: '100%',
            height: 8,
            borderRadius: 999,
          },
          '& .grade-meter-dot': {
            width: 6,
            height: 6,
            borderRadius: '50%',
            background: '#C7CBD1',
          },
          '& .grade-meter-pointer': {
            width: 0,
            height: 0,
            borderLeft: '5px solid transparent',
            borderRight: '5px solid transparent',
            borderBottom: '7px solid #1F2A44',
          },
        },
        '& .grade-meter-bar-good': { background: '#47BE62' },
        '& .grade-meter-bar-preventive': { background: '#8CC63F' },
        '& .grade-meter-bar-maintenance': { background: '#F5CE3E' },
        '& .grade-meter-bar-repair': { background: '#F0883E' },
        '& .grade-meter-bar-critical': { background: '#EF4444' },
      },
    },
    '& .degradation-verdict': {
      color: t => (t as Theme).palette.primary.main,
      fontWeight: 800,
      fontSize: FONT_SIZES.md,
    },
    '& .degradation-detail': {
      color: '#6B7280',
      fontSize: FONT_SIZES.sm,
      mt: 1,
    },
  },
  '& .advice-panel': {
    width: '100%',
    position: 'relative',
    borderRadius: 4,
    background: 'linear-gradient(180deg, #FFF7EF 0%, #FFF1E6 100%)',
    border: '1px solid #FBD9BE',
    '& .advice-header': {
      padding: 2,
      alignItems: 'center',
      gap: 1.5,
      mb: 3,
      '& .advice-header-icon': {
        display: 'flex',
        fontSize: FONT_SIZES.xl,
        color: t => (t as Theme).palette.primary.main,
      },
      '& .advice-header-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.lg,
      },
    },
    '& .advice-grid': {
      display: 'grid',
      padding: 2,
      gridTemplateColumns: {
        xs: '95%',
        md: '45% 45%',
      },
      gap: { xs: 2.5, md: 3 },
    },
    '& .advice-item': {
      gap: 1.5,
      alignItems: 'flex-start',
      '& .advice-icon': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: FONT_SIZES.md,
      },
      '& .advice-icon-search': { background: '#FDF3D8', color: '#C99A1E' },
      '& .advice-icon-broom': { background: '#E4F7E9', color: '#2E9E52' },
      '& .advice-icon-pick': { background: '#FCE0E0', color: '#D64545' },
      '& .advice-icon-calendar': { background: '#E4EEFF', color: '#2563EB' },
      '& .advice-title': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.md,
      },
      '& .advice-desc': {
        color: '#6B7280',
        fontSize: FONT_SIZES.sm,
        mt: 0.5,
      },
    },
    '& .advice-disclaimer': {
      mt: 3,
      m: 2,
      p: 2,
      borderRadius: 3,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 1,
      fontWeight: 700,
      fontSize: FONT_SIZES.sm,
      color: '#8A6D1B',
      background: '#FDF3D0',
      border: '1px solid #F6E4A8',
      '& svg': { color: '#8A6D1B', fontSize: FONT_SIZES.md, flexShrink: 0 },
    },
  },
};

export const TestimonialsStyle: SxProps = {
  width: {
    xs: '97vw',
    md: '94vw',
    lg: '92vw',
  },
  maxWidth: 1180,
  mt: 6,
  mb: 4,
  gap: 4,
  '& .section-header': {
    flexDirection: {
      xs: 'column',
      md: 'row',
    },
    justifyContent: 'space-between',
    alignItems: {
      xs: 'flex-start',
      md: 'flex-end',
    },
    gap: 2,
    '& .section-heading': {
      gap: 1,
      '& .section-eyebrow': {
        color: t => (t as Theme).palette.primary.main,
        fontWeight: 800,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        fontSize: FONT_SIZES.xs,
      },
      '& .section-title': {
        fontWeight: 800,
        lineHeight: 1.1,
        color: PALETTE_COLORS.black,
        fontSize: {
          xs: FONT_SIZES['2xl'],
          md: FONT_SIZES['4xl'],
        },
      },
    },
    '& .rating-summary': {
      alignItems: 'center',
      gap: 1,
      flexShrink: 0,
      '& .rating-stars .star': {
        color: '#F5A623',
        fontSize: FONT_SIZES.lg,
        letterSpacing: '0.05em',
      },
      '& .rating-score': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.md,
      },
      '& .rating-count': {
        color: '#6B7280',
        fontSize: FONT_SIZES.sm,
      },
    },
  },
  '& .review-carousel': {
    width: '100%',
    overflow: 'hidden',
    py: 1,
    // Fade the edges so cards slide in/out smoothly.
    maskImage: 'linear-gradient(to right, transparent 0, #000 6%, #000 94%, transparent 100%)',
    WebkitMaskImage: 'linear-gradient(to right, transparent 0, #000 6%, #000 94%, transparent 100%)',
    '&:hover .review-track': {
      animationPlayState: 'paused',
    },
    '@keyframes review-marquee': {
      from: { transform: 'translateX(0)' },
      to: { transform: 'translateX(-50%)' },
    },
  },
  '& .review-track': {
    display: 'flex',
    width: 'max-content',
    gap: 3,
    animation: 'review-marquee 40s linear infinite',
  },
  '& .review-card': {
    flexShrink: 0,
    width: {
      xs: '80vw',
      sm: '340px',
    },
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    background: PALETTE_COLORS.white,
    border: '1px solid #EFEAE0',
    borderRadius: 4,
    p: 3,
    boxShadow: '0 10px 30px -18px rgba(0,0,0,0.25)',
    '& .review-mark': {
      color: t => (t as Theme).palette.primary.light,
      fontWeight: 800,
      lineHeight: 0.6,
      fontSize: FONT_SIZES['4xl'],
    },
    '& .review-stars': {
      mt: 1,
      '& .star': {
        color: '#F5A623',
        fontSize: FONT_SIZES.md,
        letterSpacing: '0.05em',
      },
    },
    '& .review-quote': {
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
      lineHeight: 1.5,
      mt: 1.5,
      flexGrow: 1,
    },
    '& .review-divider': {
      my: 2,
      borderColor: '#EFEAE0',
    },
    '& .review-author': {
      alignItems: 'center',
      gap: 1.5,
      '& .review-avatar': {
        flexShrink: 0,
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 800,
        fontSize: FONT_SIZES.xs,
        color: PALETTE_COLORS.white,
        background: t => (t as Theme).palette.primary.main,
      },
      '& .review-name': {
        fontWeight: 800,
        color: PALETTE_COLORS.black,
        fontSize: FONT_SIZES.sm,
      },
      '& .review-role': {
        color: '#6B7280',
        fontSize: FONT_SIZES.xs,
      },
    },
  },
  '& .trust-divider': {
    borderColor: '#EFEAE0',
    width: '100%',
  },
  '& .trust-badges': {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
    },
    gap: { xs: 2, md: 3 },
    width: '100%',
  },
  '& .trust-badge': {
    alignItems: 'center',
    gap: 1.5,
    justifyContent: { xs: 'flex-start', md: 'center' },
    '& .trust-icon': {
      flexShrink: 0,
      width: 44,
      height: 44,
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: FONT_SIZES.md,
    },
    '& .trust-icon-rgpd': { background: '#E4F7E9' },
    '& .trust-icon-ssl': { background: '#E4EEFF' },
    '& .trust-icon-rge': { background: '#FDF3D8' },
    '& .trust-icon-ia': { background: PALETTE_COLORS.peach },
    '& .trust-title': {
      fontWeight: 800,
      color: PALETTE_COLORS.black,
      fontSize: FONT_SIZES.sm,
    },
    '& .trust-subtitle': {
      color: '#6B7280',
      fontSize: FONT_SIZES.xs,
    },
  },
  '& .trust-footer': {
    textAlign: 'center',
    color: '#6B7280',
    fontWeight: 600,
    fontSize: FONT_SIZES.sm,
  },
};

export const detectionResultItemStyle: SxProps = {
  border: `3px solid ${PALETTE_COLORS.pine}`,
  '& .detection-result-item-loading': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
  },
  '& .item-label-container': {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    position: 'relative',
    '& .MuiTypography-root': {
      textAlign: 'center',
      fontWeight: 'bold',
    },
    '& .color-legend': {
      position: 'absolute',
      left: 1,
      top: '50%',
      transform: 'translateY(-50%)',
      height: 20,
      width: 20,
      border: `2px solid ${PALETTE_COLORS.pine}`,
      borderRadius: '2px',
    },
  },
};
