name: CI
on: [push, pull_request, workflow_dispatch]

env:
  AWS_REGION: eu-west-3
  REACT_APP_BPARTNERS_API_URL: https://api.preprod.bpartners.app
  REACT_APP_ANNOTATOR_GEO_MERCATOR_API_URL: https://1gup5vvyyg.execute-api.eu-west-3.amazonaws.com/Prod/mercator
  REACT_APP_ANNOTATOR_GEO_PIXEL_API_URL: https://1gup5vvyyg.execute-api.eu-west-3.amazonaws.com/Prod/pixel
  REACT_APP_GEO_DETECTION_API: https://qncd60qbk0.execute-api.eu-west-3.amazonaws.com

jobs:
  tests:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ''
          workdir: ''
      - name: Connect to Bpartners typescript client AWS CodeArtifact
        run: |
          sh ./initAWS.sh bpartners ${{ secrets.BPARTNERS_TS_CLIENT_AWS_ACCESS_KEY_ID }} ${{ secrets.BPARTNERS_TS_CLIENT_AWS_SECRET_ACCESS_KEY }} ${{ env.AWS_REGION }}
          sh ./initNpmrc.sh bpartners bpartners-store npm-bpartners-app ${{ secrets.BP_CLIENT_AWS_ID }}

      - name: Connect to BPartners annotator client AWS CodeArtifact
        run: |
          sh ./initAWS.sh imagery ${{ secrets.BPARTNERS_ANNOTATOR_CLIENT_AWS_ACCESS_KEY_ID }} ${{ secrets.BPARTNERS_ANNOTATOR_CLIENT_AWS_SECRET_ACCESS_KEY }} ${{ env.AWS_REGION }}
          sh ./initNpmrc.sh imagery annotator-imagery-store npm-bpartners-imagery-app ${{ secrets.BP_ANNOTATOR_AWS_ID }}

      - run: npm install --legacy-peer-deps
      - run: |
          echo REACT_APP_BPARTNERS_API_URL=${{ env.REACT_APP_BPARTNERS_API_URL }} > .env
          echo REACT_APP_ANNOTATOR_GEO_MERCATOR_API_URL=${{ env.REACT_APP_ANNOTATOR_GEO_MERCATOR_API_URL }} >> .env
          echo REACT_APP_ANNOTATOR_GEO_PIXEL_API_URL=${{ env.REACT_APP_ANNOTATOR_GEO_PIXEL_API_URL }} >> .env
          echo REACT_APP_GEO_DETECTION_API=${{ env.REACT_APP_GEO_DETECTION_API }} >> .env
          echo LLM_ANALYSE_RESULT=${{ secrets.LLM_ANALYSE_RESULT }} >> .env

          npm test

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 17.x

      - run: rm package.json package-lock.json

      - run: |
          npm init -y
          npm install -d prettier prettier-plugin-organize-imports

      - run: npx prettier --check "src/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
