import { FONT_SIZES } from '@/utilities/theme';
import { SxProps, Theme } from '@mui/material';

/**
 * Reference palette shared with the landing hero (styles.ts) so the inner-page
 * header matches the first page. Kept local to the header styles.
 */
const REF = {
  card: '#FFFFFF',
  orange: '#E96B33',
  text: '#17181B',
  textMuted: '#6B6B6B',
  textSoft: '#4A4A4A',
  border: '#E8DFC9',
  borderStrong: '#D5CBB2',
  shadowSm: '0 2px 8px rgba(31, 24, 12, 0.04)',
  shadow: '0 10px 32px rgba(31, 24, 12, 0.08)',
  radius: '20px',
  radiusSm: '12px',
};

export const HeaderStyle: SxProps<Theme> = {
  width: { xs: '97vw', md: '94vw', lg: '92vw' },
  maxWidth: 1140,
  mx: 'auto',
  fontFamily: "'Kumbh Sans', -apple-system, 'Segoe UI', sans-serif",
  '& .MuiTypography-root': { fontFamily: 'inherit' },
  display: 'flex',
  flexDirection: 'column',
  gap: { xs: 2.5, md: 3 },
  mt: { xs: 2, md: 3 },
  mb: { xs: 2.5, md: 4 },

  '& .accent': { color: REF.orange },

  // ---- hero split: partner card (logo + info) + headline, same layout as the landing hero ----
  '& .hero-split': {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '300px 1fr' },
    gap: { xs: 3, md: 6 },
    alignItems: 'center',
    py: { xs: 2, md: 4 },
  },
  '& .partner-card': {
    background: REF.card,
    border: `1px solid ${REF.border}`,
    borderRadius: REF.radius,
    boxShadow: REF.shadow,
    maxWidth: { xs: 380, md: 'none' },
    mx: { xs: 'auto', md: 0 },
    width: '100%',
    padding: 3,
    '& .partner-card-logo': {
      width: '100%',
      aspectRatio: '4 / 3',
      borderRadius: REF.radiusSm,
      background: '#fff',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      mb: 2.25,
      overflow: 'hidden',
      '& img': { maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' },
      '& .MuiSkeleton-root': { transform: 'none', borderRadius: REF.radiusSm },
    },
    '& .partner-name': { fontSize: FONT_SIZES.lg, fontWeight: 800, color: REF.text, mb: 0.75 },
    '& .partner-addr': {
      fontSize: FONT_SIZES.xs,
      fontWeight: 600,
      color: REF.textSoft,
      lineHeight: 1.5,
      mb: 1.25,
      '& a': { color: 'inherit', textDecoration: 'none' },
      '& a:hover': { color: REF.orange },
    },
    '& .partner-contact': {
      fontSize: FONT_SIZES.xs,
      color: REF.textMuted,
      lineHeight: 1.6,
      pt: 1.5,
      borderTop: `1px dashed ${REF.borderStrong}`,
      '& a': { color: 'inherit', textDecoration: 'none' },
      '& a:hover': { color: REF.orange },
      '& strong': { color: REF.text, fontWeight: 600 },
    },
  },
  '& .hero-content': {
    textAlign: 'center',
    alignItems: 'center',
    '& .hero-title': {
      fontWeight: 800,
      lineHeight: 1.05,
      letterSpacing: '-0.025em',
      color: REF.text,
      maxWidth: 640,
      mb: 2.25,
      fontSize: { xs: '2.375rem', md: '3.75rem' },
    },
    '& .hero-lead': { fontSize: FONT_SIZES.lg, color: REF.textMuted, maxWidth: 560, lineHeight: 1.55 },
  },

  // ---- FR badge ----
  '& .fr-badge': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    py: '7px',
    px: '14px',
    pl: 1,
    background: '#fff',
    border: `1.5px solid ${REF.border}`,
    borderRadius: 999,
    fontSize: FONT_SIZES.xs,
    fontWeight: 600,
    color: REF.text,
    boxShadow: REF.shadowSm,
    lineHeight: 1,
    whiteSpace: 'nowrap',
    mb: 2.5,
    '& em': { fontStyle: 'normal', fontWeight: 500, color: REF.textMuted },
  },
  '& .fr-flag': {
    display: 'inline-flex',
    alignItems: 'center',
    width: 22,
    height: 16,
    borderRadius: '3px',
    overflow: 'hidden',
    boxShadow: '0 0 0 1px rgba(0,0,0,0.08)',
    flexShrink: 0,
    '& span': { display: 'block', height: '100%', flex: 1 },
    '& .fr-blue': { background: '#002395' },
    '& .fr-white': { background: '#FFFFFF' },
    '& .fr-red': { background: '#ED2939' },
  },

  // ---- Steps strip (wired to wizard progress) ----
  '& .hero-steps': {
    width: '100%',
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr 1fr', lg: 'repeat(4, 1fr)' },
    gap: { xs: 1.5, md: 2.5 },
    '& .step-item': {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      gap: 0.5,
      px: 1,
    },
    '& .step-index': {
      width: 40,
      height: 40,
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontWeight: 800,
      fontSize: FONT_SIZES.md,
      background: '#fff',
      border: `2px solid ${REF.borderStrong}`,
      color: '#9aa2ad',
      transition: 'all 200ms linear',
      zIndex: 1,
    },
    '& .step-item.active .step-index': {
      background: REF.orange,
      borderColor: REF.orange,
      color: '#fff',
      boxShadow: '0 8px 20px -8px rgba(233, 107, 51, 0.6)',
    },
    '& .step-item.done .step-index': {
      borderColor: REF.orange,
      color: REF.orange,
    },
    '& .step-label': {
      fontWeight: 700,
      fontSize: FONT_SIZES.md,
      color: REF.text,
      mt: 0.25,
    },
    '& .step-subtitle': {
      fontWeight: 700,
      fontSize: FONT_SIZES.sm,
      color: REF.text,
    },
    '& .step-desc': {
      fontSize: FONT_SIZES.sm,
      color: REF.textMuted,
      lineHeight: 1.4,
      display: { xs: 'none', md: 'block' },
    },
  },
};
